#!/usr/bin/env python3
"""Generate celeste_cart.h (embedded benchmark asset) from celeste.p8.

The Celeste Classic cart (Maddy Thorson & Noel Berry) is third-party game code, so
celeste.p8 and the generated celeste_cart.h are .gitignored — they are NOT committed
or redistributed. This script (which IS committed) regenerates them locally:

    python3 gen_celeste_cart.py           # fetches celeste.p8 if missing, writes celeste_cart.h

celeste.p8 is fetched from DavidVentura's PicoPico (same copy we benchmark against).
Run it once after cloning, before building pico-e32-luabench.
"""
import os, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
P8   = os.path.join(HERE, "celeste.p8")
OUT  = os.path.join(HERE, "celeste_cart.h")
URL  = "https://raw.githubusercontent.com/DavidVentura/PicoPico/master/carts/celeste.p8"

GFX_W, GFX_H = 128, 128          # PICO-8 sprite sheet: 16x16 sprites of 8x8
GFX_PX = GFX_W * GFX_H

def ensure_cart():
    if os.path.exists(P8):
        return
    print(f"celeste.p8 not found; fetching from {URL}")
    try:
        urllib.request.urlretrieve(URL, P8)
    except Exception as e:
        sys.exit(f"failed to fetch celeste.p8: {e}\nDownload it manually to {P8}")

def section(lines, name):
    out, inn = [], False
    for l in lines:
        if l.startswith("__"):
            inn = (l.strip() == "__" + name + "__"); continue
        if inn: out.append(l)
    return out

def gfx_pixels(lines):
    """__gfx__ -> 128x128 palette indices, one byte per pixel (row-major).

    The section is one hex char per pixel, left-to-right — NOT the nibble-swapped packing
    PICO-8 uses in its own sprite memory, so this is a straight char->value decode. Stored
    unpacked (16 KB) rather than 4 bpp (8 KB): it keeps the spr() inner loop free of
    shift/mask per pixel, and 16 KB of flash is noise against the 78% free partition.
    Short/absent sheets are zero-padded — carts need not fill all 128 rows.
    """
    px = [int(c, 16) for c in "".join(section(lines, "gfx")) if c in "0123456789abcdefABCDEF"]
    if len(px) > GFX_PX:
        sys.exit(f"__gfx__ too large: {len(px)} px (want <= {GFX_PX})")
    return px + [0] * (GFX_PX - len(px))

def main():
    ensure_cart()
    lines = open(P8, encoding="utf-8", errors="replace").read().splitlines()
    lua = "\n".join(section(lines, "lua"))
    gff = "".join(section(lines, "gff"))
    mp  = "".join(section(lines, "map"))
    gff_b = [int(gff[i:i+2], 16) for i in range(0, len(gff), 2)]
    map_b = [int(mp[i:i+2],  16) for i in range(0, len(mp),  2)]
    gfx_b = gfx_pixels(lines)
    if len(gff_b) != 256 or len(map_b) != 4096:
        sys.exit(f"unexpected sizes: gff={len(gff_b)} (want 256), map={len(map_b)} (want 4096)")
    if max(gfx_b) > 15:
        sys.exit(f"__gfx__ has a palette index > 15 ({max(gfx_b)})")
    delim = "C3LST3"
    with open(OUT, "w") as f:
        f.write("// GENERATED by gen_celeste_cart.py from celeste.p8 — do not edit, do not commit.\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define CELESTE_GFX_W {GFX_W}\n#define CELESTE_GFX_H {GFX_H}\n")
        f.write(f'static const char CELESTE_LUA[] = R"{delim}(\n{lua}\n){delim}";\n')
        f.write(f"static uint8_t CELESTE_MAP[{len(map_b)}] = {{{','.join(map(str, map_b))}}};\n")
        f.write(f"static const uint8_t CELESTE_GFF[{len(gff_b)}] = {{{','.join(map(str, gff_b))}}};\n")
        f.write(f"// sprite sheet: {GFX_W}x{GFX_H}, one palette index per byte; sprite n at (n%16*8, n/16*8)\n")
        f.write(f"static const uint8_t CELESTE_GFX[{len(gfx_b)}] = {{{','.join(map(str, gfx_b))}}};\n")
    print(f"wrote {OUT}  (lua {len(lua)} chars, map {len(map_b)} B, gff {len(gff_b)} B, "
          f"gfx {len(gfx_b)} B = {GFX_W}x{GFX_H})")

if __name__ == "__main__":
    main()
